---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        exclude: ^fastkml/tests/base.py
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.76"
    hooks:
      - id: flynt
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/hakancelikdev/unimport
    rev: 004b5dd0c8112330275beb52c4ccfce016a4b945
    hooks:
      - id: unimport
        args: [--remove, --include-star-import, --ignore-init, --gitignore]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py37-plus"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    - id: check-manifest
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  #   rev: v1.0.1
  #   hooks:
  #     - id: rst-linter
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910
  #   hooks:
  #     - id: mypy
...
